PS C:\Users\Usuario\Desktop\PrimerDespliegue> pip install virtualenv
Requirement already satisfied: virtualenv in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (20.24.3)
Requirement already satisfied: distlib<1,>=0.3.7 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from virtualenv) (0.3.7)
Requirement already satisfied: filelock<4,>=3.12.2 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from virtualenv) (3.12.2)
Requirement already satisfied: platformdirs<4,>=3.9.1 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from virtualenv) (3.10.0)

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
PS C:\Users\Usuario\Desktop\PrimerDespliegue> python -m virtualenv venv
created virtual environment CPython3.11.4.final.0-64 in 822ms
  creator CPython3Windows(dest=C:\Users\Usuario\Desktop\PrimerDespliegue\venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\Usuario\AppData\Local\pypa\virtualenv)      
    added seed packages: pip==23.2.1, setuptools==68.0.0, wheel==0.41.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
PS C:\Users\Usuario\Desktop\PrimerDespliegue> .\venv\Scripts\activate
(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> pip install django
Collecting django
  Obtaining dependency information for django from https://files.pythonhosted.org/packages/7f/9e/fc6bab255ae10bc57fa2f65646eace3d5405fbb7f5678b90140052d1db0f/Django-4.2.4-py3-none-any.whl.metadata
  Using cached Django-4.2.4-py3-none-any.whl.metadata (4.1 kB)
Collecting asgiref<4,>=3.6.0 (from django)
  Obtaining dependency information for asgiref<4,>=3.6.0 from https://files.pythonhosted.org/packages/9b/80/b9051a4a07ad231558fcd8ffc89232711b4e618c15cb7a392a17384bbeef/asgiref-3.7.2-py3-none-any.whl.metadata
  Using cached asgiref-3.7.2-py3-none-any.whl.metadata (9.2 kB)
Collecting sqlparse>=0.3.1 (from django)
  Using cached sqlparse-0.4.4-py3-none-any.whl (41 kB)
Collecting tzdata (from django)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Using cached Django-4.2.4-py3-none-any.whl (8.0 MB)
Using cached asgiref-3.7.2-py3-none-any.whl (24 kB)
Installing collected packages: tzdata, sqlparse, asgiref, django
Successfully installed asgiref-3.7.2 django-4.2.4 sqlparse-0.4.4 tzdata-2023.3
(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> pip install djangorestframework
Collecting djangorestframework
  Using cached djangorestframework-3.14.0-py3-none-any.whl (1.1 MB)
Requirement already satisfied: django>=3.0 in c:\users\usuario\desktop\primerdespliegue\venv\lib\site-packages (from djangorestframework) (4.2.4)
Collecting pytz (from djangorestframework)
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Requirement already satisfied: asgiref<4,>=3.6.0 in c:\users\usuario\desktop\primerdespliegue\venv\lib\site-packages (from django>=3.0->djangorestframework) (3.7.2)
Requirement already satisfied: sqlparse>=0.3.1 in c:\users\usuario\desktop\primerdespliegue\venv\lib\site-packages (from django>=3.0->djangorestframework) (0.4.4)
Requirement already satisfied: tzdata in c:\users\usuario\desktop\primerdespliegue\venv\lib\site-packages (from django>=3.0->djangorestframework) (2023.3)    
Installing collected packages: pytz, djangorestframework
Successfully installed djangorestframework-3.14.0 pytz-2023.3
(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> django-admin startproject PrimerDespliegue .
(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.        
Run 'python manage.py migrate' to apply them.
August 20, 2023 - 08:38:40
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[20/Aug/2023 08:38:42] "GET / HTTP/1.1" 200 10664
(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> python manage.py startapp projects
(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> python manage.py runserver        
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.        
Run 'python manage.py migrate' to apply them.
August 20, 2023 - 08:40:23
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[20/Aug/2023 08:40:27] "GET / HTTP/1.1" 200 10664
C:\Users\Usuario\Desktop\PrimerDespliegue\projects\models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\management\__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\projects\models.py", line 4, in <module>
    class Project(models.Model):
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\projects\models.py", line 8, in Project
    created_at = models.DateTimeField(auto_now_add=true)
                                                   ^^^^
NameError: name 'true' is not defined. Did you mean: 'True'?
C:\Users\Usuario\Desktop\PrimerDespliegue\projects\models.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.        
Run 'python manage.py migrate' to apply them.
August 20, 2023 - 08:42:42
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> python manage.py makemigrations
Migrations for 'projects':
  projects\migrations\0001_initial.py
    - Create model Project
(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> python manage.py migrate       
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, projects, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying projects.0001_initial... OK
  Applying sessions.0001_initial... OK
(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 08:55:05
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[20/Aug/2023 08:55:07] "GET / HTTP/1.1" 200 10664
Not Found: /api/
[20/Aug/2023 08:55:10] "GET /api/ HTTP/1.1" 404 2099
Not Found: /api/
[20/Aug/2023 08:55:11] "GET /api/ HTTP/1.1" 404 2099
Not Found: /projects/
[20/Aug/2023 08:55:22] "GET /projects/ HTTP/1.1" 404 2114
Not Found: /projects/
[20/Aug/2023 08:55:22] "GET /projects/ HTTP/1.1" 404 2114
Not Found: /api/projects/
[20/Aug/2023 08:55:35] "GET /api/projects/ HTTP/1.1" 404 2126
Not Found: /api/projects
[20/Aug/2023 08:55:37] "GET /api/projects HTTP/1.1" 404 2123
(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\PrimerDespliegue\urls.py", line 23, in <module>
    path('', include('projects.urls'))
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\projects\urls.py", line 2, in <module>
    from .api import ProjectViewSet
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\projects\api.py", line 1, in <module>
    from models import Project
ModuleNotFoundError: No module named 'models'
C:\Users\Usuario\Desktop\PrimerDespliegue\projects\api.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\checks\urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\checks\urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\PrimerDespliegue\urls.py", line 23, in <module>
    path('', include('projects.urls'))
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\projects\urls.py", line 2, in <module>
    from .api import ProjectViewSet
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\projects\api.py", line 3, in <module>
    from serializers import ProjectSerializers
ModuleNotFoundError: No module named 'serializers'
C:\Users\Usuario\Desktop\PrimerDespliegue\projects\api.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 09:02:53
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[20/Aug/2023 09:03:03] "GET / HTTP/1.1" 200 5280
[20/Aug/2023 09:03:03] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[20/Aug/2023 09:03:03] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[20/Aug/2023 09:03:03] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[20/Aug/2023 09:03:03] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[20/Aug/2023 09:03:03] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
[20/Aug/2023 09:03:03] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[20/Aug/2023 09:03:03] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[20/Aug/2023 09:03:03] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[20/Aug/2023 09:03:03] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[20/Aug/2023 09:03:03] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[20/Aug/2023 09:03:03] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
Not Found: /api/
[20/Aug/2023 09:03:51] "GET /api/ HTTP/1.1" 404 3304
[20/Aug/2023 09:03:53] "GET /api/projects HTTP/1.1" 301 0
Internal Server Error: /api/projects/
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\generics.py", line 63, in get_queryset
    assert self.queryset is not None, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'ProjectViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
[20/Aug/2023 09:03:54] "GET /api/projects/ HTTP/1.1" 500 98752
C:\Users\Usuario\Desktop\PrimerDespliegue\projects\api.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 09:04:18
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Internal Server Error: /api/projects/
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 574, in get_raw_data_form
    media_types = [parser.media_type for parser in view.parser_classes]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 574, in <listcomp>
    media_types = [parser.media_type for parser in view.parser_classes]
                   ^^^^^^^^^^^^^^^^^
AttributeError: type object 'AllowAny' has no attribute 'media_type'
[20/Aug/2023 09:04:20] "GET /api/projects/ HTTP/1.1" 500 93094
C:\Users\Usuario\Desktop\PrimerDespliegue\projects\serializers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 09:05:00
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Internal Server Error: /api/projects/
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 574, in get_raw_data_form
    media_types = [parser.media_type for parser in view.parser_classes]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 574, in <listcomp>
    media_types = [parser.media_type for parser in view.parser_classes]
                   ^^^^^^^^^^^^^^^^^
AttributeError: type object 'AllowAny' has no attribute 'media_type'
[20/Aug/2023 09:05:03] "GET /api/projects/ HTTP/1.1" 500 93094
C:\Users\Usuario\Desktop\PrimerDespliegue\projects\api.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 09:05:14
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\Usuario\Desktop\PrimerDespliegue\projects\api.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 09:05:32
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Internal Server Error: /api/projects/
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\views.py", line 492, in dispatch
    request = self.initialize_request(request, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\viewsets.py", line 146, in initialize_request
    request = super().initialize_request(request, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\views.py", line 393, in initialize_request
    parsers=self.get_parsers(),
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\views.py", line 266, in get_parsers
    return [parser() for parser in self.parser_classes]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\views.py", line 266, in <listcomp>
    return [parser() for parser in self.parser_classes]
            ^^^^^^^^
TypeError: 'AllowAny' object is not callable
[20/Aug/2023 09:05:33] "GET /api/projects/ HTTP/1.1" 500 93541
C:\Users\Usuario\Desktop\PrimerDespliegue\projects\api.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 09:06:31
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Internal Server Error: /api/projects/
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
                 ^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 1124, in get_field_names
    assert not (fields is None and exclude is None), (
                                   ^^^^^^^^^^^^^^^
AssertionError: ("Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the ProjectSerializers serializer.",)
[20/Aug/2023 09:06:34] "GET /api/projects/ HTTP/1.1" 500 123103
C:\Users\Usuario\Desktop\PrimerDespliegue\projects\api.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 09:08:19
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Internal Server Error: /api/projects/
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
                 ^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 1124, in get_field_names
    assert not (fields is None and exclude is None), (
                                   ^^^^^^^^^^^^^^^
AssertionError: ("Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the ProjectSerializers serializer.",)
[20/Aug/2023 09:08:21] "GET /api/projects/ HTTP/1.1" 500 123103
C:\Users\Usuario\Desktop\PrimerDespliegue\projects\api.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 09:08:58
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\Usuario\Desktop\PrimerDespliegue\projects\serializers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 09:09:20
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Internal Server Error: /api/projects/
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
                 ^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 1124, in get_field_names
    assert not (fields is None and exclude is None), (
                                   ^^^^^^^^^^^^^^^
AssertionError: ("Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the ProjectSerializers serializer.",)
[20/Aug/2023 09:09:24] "GET /api/projects/ HTTP/1.1" 500 123103
Internal Server Error: /api/projects/
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
                 ^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\rest_framework\serializers.py", line 1124, in get_field_names
    assert not (fields is None and exclude is None), (
                                   ^^^^^^^^^^^^^^^
AssertionError: ("Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the ProjectSerializers serializer.",)
[20/Aug/2023 09:09:25] "GET /api/projects/ HTTP/1.1" 500 123103
C:\Users\Usuario\Desktop\PrimerDespliegue\projects\serializers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 09:09:39
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

C:\Users\Usuario\Desktop\PrimerDespliegue\projects\serializers.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
August 20, 2023 - 09:10:00
Django version 4.2.4, using settings 'PrimerDespliegue.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

[20/Aug/2023 09:10:01] "GET /api/projects/ HTTP/1.1" 200 9095
[20/Aug/2023 09:10:01] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[20/Aug/2023 09:10:01] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[20/Aug/2023 09:10:01] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[20/Aug/2023 09:10:01] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[20/Aug/2023 09:10:01] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[20/Aug/2023 09:10:01] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[20/Aug/2023 09:10:01] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[20/Aug/2023 09:10:01] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[20/Aug/2023 09:10:01] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[20/Aug/2023 09:10:01] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[20/Aug/2023 09:10:01] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[20/Aug/2023 09:10:36] "GET /api/projects/ HTTP/1.1" 200 9095
[20/Aug/2023 09:11:12] "POST /api/projects/ HTTP/1.1" 201 9383
[20/Aug/2023 09:11:21] "GET /api/projects/ HTTP/1.1" 200 9375
[20/Aug/2023 09:12:18] "GET /api/projects HTTP/1.1" 301 0
[20/Aug/2023 09:12:18] "GET /api/projects/ HTTP/1.1" 200 131
[20/Aug/2023 09:14:23] "POST /api/projects/ HTTP/1.1" 201 135
[20/Aug/2023 09:14:36] "GET /api/projects/ HTTP/1.1" 200 267
[20/Aug/2023 09:14:41] "GET /api/projects/1 HTTP/1.1" 301 0
[20/Aug/2023 09:14:41] "GET /api/projects/1/ HTTP/1.1" 200 129
[20/Aug/2023 09:14:43] "GET /api/projects/2 HTTP/1.1" 301 0
[20/Aug/2023 09:14:43] "GET /api/projects/2/ HTTP/1.1" 200 135
[20/Aug/2023 09:14:59] "DELETE /api/projects/2 HTTP/1.1" 301 0
[20/Aug/2023 09:14:59] "DELETE /api/projects/2/ HTTP/1.1" 204 0
[20/Aug/2023 09:15:03] "GET /api/projects/2 HTTP/1.1" 301 0
Not Found: /api/projects/2/
[20/Aug/2023 09:15:03] "GET /api/projects/2/ HTTP/1.1" 404 23
Internal Server Error: /api/projects/2
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/projects/2/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings. 
[20/Aug/2023 09:15:08] "POST /api/projects/2 HTTP/1.1" 500 69596
[20/Aug/2023 09:15:14] "POST /api/projects/ HTTP/1.1" 201 135
Internal Server Error: /api/projects/1
Traceback (most recent call last):
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usuario\Desktop\PrimerDespliegue\venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/api/projects/1/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.   
[20/Aug/2023 09:16:00] "PUT /api/projects/1 HTTP/1.1" 500 69580
Bad Request: /api/projects/1/
[20/Aug/2023 09:16:34] "PUT /api/projects/1/ HTTP/1.1" 400 108
[20/Aug/2023 09:16:52] "GET /api/projects/1 HTTP/1.1" 301 0
[20/Aug/2023 09:16:52] "GET /api/projects/1/ HTTP/1.1" 200 129
Bad Request: /api/projects/1/
[20/Aug/2023 09:17:07] "PUT /api/projects/1/ HTTP/1.1" 400 78
[20/Aug/2023 09:17:58] "PATCH /api/projects/1/ HTTP/1.1" 200 169
[20/Aug/2023 09:18:12] "PATCH /api/projects/1/ HTTP/1.1" 200 171
(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> git init 
git : El término 'git' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable. Compruebe si escribió correctamente el 
nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ git init
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue> git --v
git : El término 'git' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable. Compruebe si escribió correctamente el
nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ git --v
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

(venv) PS C:\Users\Usuario\Desktop\PrimerDespliegue>